version: "3"
services:
  mysql:
    image: mysql:5
    enviroment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: paasdb
      MYSQL_USER: paasdb_user
      MYSQL_PASSWORD: secret
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 3
    volumes:
      - type: volume
        source: mysqlDB
        target: /var/lib/mysql
    networks:
      - networks

  performance:
    build:
      context: ./webappbuild
      dockerfile: Dockerfile
    volumes:
      - application-volume:/home/webapp/App42PaaS-Java-MySQL-Sample/target/
      - properties-volume:/home/webapp/App42PaaS-Java-MySQL-Sample/WebContent/

  openwebprod:
    build:
      context: ./openwebprod
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - application-volume:/usr/local/tomcat/webapps/
      - properties-volume:/usr/local/tomcat/ROOT/
    networks:
      - networks

volumes:
  database-volume:
  application-volume:
  properties-volume:
    networks:
      - networks